import { GlobalLanguageCode } from '@/global.interface'

export type SupportedDictService =
  | 'google'
  | 'naver_dictionary'
  | 'dictionary_dot_come'
  | 'urban_dictionary'

export type AvailableDictCode = {
  id: string
  serviceName: SupportedDictService
  dictFrom: GlobalLanguageCode | 'ALL'
  dictTo: GlobalLanguageCode | 'ALL'
  prefixUrl: string
  // suffixUrl: string // suffixUrl is not yet supported as it is not needed for now
}

/** List of third-party supported dictionary services
 * Its id is generated by concatenating serviceName, dictFrom, and dictTo.
 * It is domain's responsibility to make sure that the id is unique.
 */
const privateAvailableDictCodes: Omit<AvailableDictCode, 'id'>[] = [
  {
    serviceName: 'google',
    dictFrom: 'ALL',
    dictTo: 'ALL',
    prefixUrl: 'https://www.google.com/search?q=define%20',
  },
  {
    serviceName: 'naver_dictionary',
    dictFrom: 'ko',
    dictTo: 'ko',
    prefixUrl: 'https://ko.dict.naver.com/#/search?range=all&query=',
  },
  {
    serviceName: 'naver_dictionary',
    dictFrom: 'en',
    dictTo: 'ko',
    prefixUrl: 'https://en.dict.naver.com/#/search?range=all&query=',
  },
  {
    serviceName: 'naver_dictionary',
    dictFrom: 'ja',
    dictTo: 'ko',
    prefixUrl: 'https://ja.dict.naver.com/#/search?range=all&query=',
  },
  {
    serviceName: 'naver_dictionary',
    dictFrom: 'zh',
    dictTo: 'ko',
    prefixUrl: 'https://zh.dict.naver.com/#/search?range=all&query=',
  },
  {
    serviceName: 'naver_dictionary',
    dictFrom: 'ko',
    dictTo: 'ja',
    prefixUrl: 'https://korean.dict.naver.com/#/search?range=all&query=',
  },
  {
    serviceName: 'dictionary_dot_come',
    dictFrom: 'en',
    dictTo: 'en',
    prefixUrl: 'https://www.dictionary.com/browse/',
  },
  {
    serviceName: 'urban_dictionary',
    dictFrom: 'en',
    dictTo: 'en',
    prefixUrl: 'https://www.urbandictionary.com/define.php?term=',
  },
]
export const availableDictCodes: AvailableDictCode[] =
  privateAvailableDictCodes.map((dict) => ({
    id: `${dict.serviceName}_${dict.dictFrom}_${dict.dictTo}`,
    ...dict,
  }))
