name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ajktown --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ajktown/api:latest

    - name: Push the Docker image
      run: docker push ajktown/api:latest
